import { useEffect, useMemo, useState } from 'react';
import {
  AlertTriangle, ArrowLeft, ArrowRight, BrainCircuit, CheckCircle2, ChevronRight,
  Clock3, FileText, GitBranch, HeartPulse, History, Info, Network, Search,
  ShieldCheck, Sparkles, Stethoscope, X
} from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { hacApi } from '../api/hacApi';
import type { FindingCard, HacInvestigation, ReviewOutcome, ReviewerNote, TimelineEvent } from '../api/hacTypes';
import { useToast } from '../components/Feedback';

type EvidenceKey = FindingCard['key'];
const icons: Record<EvidenceKey, any> = { timing: Clock3, path: Network, intervention: HeartPulse, coding: FileText, history: History };
const reviewOptions: Array<[ReviewOutcome,string]> = [
  ['CONFIRM_CONCERN','Confirm HAC concern'],['EXPECTED_PROGRESSION','Expected clinical progression'],['NEED_MORE_INFORMATION','Need more information'],
  ['ROUTE_OTHER_PROVIDER','Route to another provider'],['MONITOR','Monitor only'],['NO_CONCERN','No concern'],['ESCALATE','Escalate']
];

export default function ClaimDetails(){
  const {claimId=''}=useParams(); const nav=useNavigate(); const toast=useToast();
  const [data,setData]=useState<HacInvestigation|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const [selectedEvidence,setSelectedEvidence]=useState<EvidenceKey|null>(null); const [selectedJourney,setSelectedJourney]=useState<TimelineEvent|null>(null);
  const [technicalOpen,setTechnicalOpen]=useState(false); const [reviewOpen,setReviewOpen]=useState(false); const [notesOpen,setNotesOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false);
  const [decision,setDecision]=useState<ReviewOutcome|''>(''); const [rationale,setRationale]=useState(''); const [note,setNote]=useState(''); const [reviewerId,setReviewerId]=useState(''); const [reviewerName,setReviewerName]=useState(''); const [reviewerRole,setReviewerRole]=useState(''); const [actionBusy,setActionBusy]=useState(false); const [actionMessage,setActionMessage]=useState('');
  const [notes,setNotes]=useState<ReviewerNote[]>([]);

  const load=()=>{setLoading(true);setError('');Promise.all([hacApi.getInvestigation(claimId),hacApi.getNotes(claimId)]).then(([inv,n])=>{setData(inv);setNotes(n.notes)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[claimId]);
  const currentEvidence=useMemo(()=>data?.findingsCards.find(f=>f.key===selectedEvidence)??null,[data,selectedEvidence]);
  if(loading)return <div className="card api-state">Loading investigation from backend…</div>;
  if(error||!data)return <div className="card api-state api-error"><strong>Could not load investigation</strong><span>{error}</span><button className="btn primary" onClick={load}>Retry</button></div>;

  const compB=data.technicalBreakdown.componentB, compC=data.technicalBreakdown.componentC, compD=data.technicalBreakdown.componentD, compE=data.technicalBreakdown.componentE, compA=data.technicalBreakdown.componentA;
  const critical=data.signalResult.level==='HIGH';
  const relatednessText=compC.outcome==='RECOGNIZED_PROGRESSION'?'Recognized progression':compC.outcome==='UNKNOWN'?'Relationship unknown':'No recognized progression';
  const keyCondition=data.timeline.find(e=>e.eventType==='diagnosis' && e.status!=='normal')?.subtitle || data.findingsCards.find(f=>f.key==='timing')?.headline || 'New condition detected';

  const saveNote=async()=>{if(!note.trim()||!reviewerName.trim()||!reviewerRole.trim())return;setActionBusy(true);setActionMessage('');try{const created=await hacApi.addNote(claimId,{author:reviewerName.trim(),authorRole:reviewerRole.trim(),content:note.trim()});setNotes(v=>[...v,created]);setNote('');setNotesOpen(false);setActionMessage('');toast.show('success','Note saved','The reviewer note was persisted.');await load()}catch(e:any){setActionMessage('');toast.show('error','Could not save note',e.message)}finally{setActionBusy(false)}};
  const saveReview=async()=>{if(!decision||!rationale.trim()||!reviewerId.trim()||!reviewerName.trim())return;setActionBusy(true);setActionMessage('');try{await hacApi.submitReview(claimId,{outcome:decision,rationale:rationale.trim(),reviewerId:reviewerId.trim(),reviewerName:reviewerName.trim()});setReviewOpen(false);setDecision('');setRationale('');setActionMessage('');toast.show('success','Review saved','The human review decision was persisted.');await load()}catch(e:any){setActionMessage('');toast.show('error','Could not save review',e.message)}finally{setActionBusy(false)}};

  return <div className="hac-v3-page">
    <div className="hac-v3-topbar"><button className="v3-ghost-btn" onClick={()=>nav('/claims')}><ArrowLeft size={17}/> Review Queue</button><div className="v3-topbar-right"><button className="v3-icon-btn" title="Search" onClick={()=>setSearchOpen(true)}><Search size={17}/></button><button className="v3-secondary-btn" onClick={()=>setNotesOpen(true)}>Add note ({notes.length})</button><button className="v3-primary-btn" onClick={()=>setReviewOpen(true)}>Review case <ArrowRight size={16}/></button></div></div>
    {actionMessage&&<div className="api-toast">{actionMessage}</div>}

    <header className="v3-case-header"><div><div className="v3-kicker">HAC SIGNAL · LIVE CLAIM INVESTIGATION</div><h1>{data.signalResult.summaryHeadline}</h1><p>{data.claimId} · Patient {data.patientId} · {data.provider.displayName}</p></div><div className="v3-case-badges"><span className={`v3-pill ${critical?'critical':''}`}><AlertTriangle size={14}/> {data.signalResult.level} priority</span><span className="v3-pill"><ShieldCheck size={14}/> {data.workflow.reviewStatus.replace(/_/g,' ')}</span></div></header>

    <section className="v3-story-grid"><article className="v3-score-hero"><div className="v3-score-donut"><strong>{data.signalResult.score}</strong><span>/100</span></div><div className="v3-score-copy"><span>Overall signal</span><h2>{data.signalResult.summaryHeadline}</h2><p>{data.signalResult.summaryDescription}</p><div className="v3-hero-actions"><button onClick={()=>setTechnicalOpen(true)}>How was this calculated? <ChevronRight size={14}/></button><button onClick={()=>data.timeline[0]&&setSelectedJourney(data.timeline[0])}>Show patient journey <ChevronRight size={14}/></button></div></div></article>
      <article className="v3-summary-panel"><div className="v3-summary-item"><span>What changed?</span><strong>{keyCondition}</strong><small>{compB.elapsedHoursFromAdmission!=null?`First seen ${compB.elapsedHoursFromAdmission}h after admission`:compB.bandLabel}</small></div><div className="v3-summary-item"><span>What made it serious?</span><strong>{compD.categoryLabel}</strong><small>{compD.triggerProcedureDescription||'Intervention evidence'}</small></div><div className="v3-summary-item"><span>Does it fit the original illness?</span><strong className={compC.outcome==='UNRELATED'?'v3-danger-text':''}>{relatednessText}</strong><small>{compC.reasoning}</small></div><div className="v3-summary-item"><span>What happens now?</span><strong>Human reviewer decides</strong><small>No automatic denial · {data.workflow.notesCount} note(s)</small></div></article>
    </section>

    <section className="v3-section"><div className="v3-section-heading"><div><span>WHY THIS CLAIM WAS FLAGGED</span><h2>Evidence story</h2><p>Every card comes directly from the investigation API. Open it for the underlying evidence.</p></div><div className="v3-confidence"><BrainCircuit size={16}/><span>AI path evidence</span><strong>{data.clinicalPath.aiEvidenceAvailable?(data.clinicalPath.deviationConfidence||'Available'):'Not connected'}</strong></div></div>
      <div className="v3-evidence-grid">{data.findingsCards.map(f=>{const Icon=icons[f.key];return <button key={f.key} className={`v3-evidence-card ${f.tone}`} onClick={()=>setSelectedEvidence(f.key)}><div className="v3-evidence-card-top"><div className="v3-evidence-icon"><Icon size={19}/></div><span>{f.level}</span></div><h3>{f.title}</h3><p>{f.headline}</p><div className="v3-evidence-card-footer"><span>View evidence</span><div><strong>{f.points}</strong><small>/{f.maxPoints}</small><ChevronRight size={16}/></div></div></button>})}</div>
    </section>

    <section className="v3-section"><div className="v3-section-heading"><div><span>PATIENT JOURNEY</span><h2>See where the journey changed</h2><p>Timeline events are generated by the backend from claim data.</p></div><button className="v3-secondary-btn" onClick={()=>nav(`/claims/${claimId}/timeline`)}>Open full timeline</button></div><div className="v3-journey">{data.timeline.map((item,index)=><button key={item.id} className={`v3-journey-step ${item.status}`} onClick={()=>setSelectedJourney(item)}><div className="v3-journey-index">{index+1}</div><div className="v3-journey-line"/><span>{item.formattedDateTime||new Date(item.dateTime).toLocaleString()}</span><strong>{item.title}</strong><small>{item.subtitle}</small><em>Open details <ChevronRight size={12}/></em></button>)}</div></section>

    <section className="v3-two-column"><article className="v3-panel v3-path-panel"><div className="v3-panel-heading"><div><span>CLINICAL PATH</span><h2>Expected vs actual journey</h2></div><button onClick={()=>setSelectedEvidence('path')}>Explain <ChevronRight size={14}/></button></div><PathRows expected={data.clinicalPath.expected} actual={data.clinicalPath.actual}/><div className="v3-ai-strip"><Sparkles size={17}/><div><span>AI supporting evidence</span><strong>{data.clinicalPath.aiEvidenceAvailable?`${data.clinicalPath.similarityPercent ?? '—'}% similarity · ${data.clinicalPath.deviationConfidence ?? '—'} confidence`:'AI model not connected — no AI evidence is shown'}</strong></div><button onClick={()=>setSelectedEvidence('path')}>See why</button></div><small className="api-source-label">{data.clinicalPath.aiEvidenceStatus}</small></article>
      <article className="v3-panel"><div className="v3-panel-heading"><div><span>DATA QUALITY</span><h2>Can this result be trusted?</h2></div><span className={`v3-pill ${data.dataQuality.isReliable?'good':'critical'}`}><CheckCircle2 size={14}/> {data.dataQuality.overallStatus}</span></div><div className="v3-check-list">{data.dataQuality.flags.length===0?<button><CheckCircle2/><div><strong>No data quality warnings</strong><span>Required evidence is available for this calculation.</span></div><ChevronRight/></button>:data.dataQuality.flags.map(flag=><button key={flag.code} onClick={()=>setTechnicalOpen(true)}><Info/><div><strong>{flag.code}</strong><span>{flag.message}</span></div><ChevronRight/></button>)}</div></article>
    </section>

    <section className="v3-review-banner"><div><Stethoscope size={22}/><div><span>NEXT STEP</span><h2>Human review is required before any payment decision</h2><p>The signal routes the case; it does not deny it automatically.</p></div></div><button className="v3-primary-btn" onClick={()=>setReviewOpen(true)}>Start review <ArrowRight size={16}/></button></section>

    {currentEvidence&&<div className="v3-overlay" onClick={()=>setSelectedEvidence(null)}><aside className="v3-drawer" onClick={e=>e.stopPropagation()}><div className="v3-drawer-header"><div><span>EVIDENCE DETAILS</span><h2>{currentEvidence.title}</h2></div><button onClick={()=>setSelectedEvidence(null)}><X/></button></div><div className="v3-drawer-score"><div><strong>{currentEvidence.points}</strong><span>/{currentEvidence.maxPoints}</span></div><p>{currentEvidence.level}</p></div><div className="v3-detail-block"><span>What the system found</span><h3>{currentEvidence.headline}</h3><p>{currentEvidence.summary}</p></div>{currentEvidence.key==='timing'&&<TimingDetail b={compB}/>} {currentEvidence.key==='path'&&<PathDetail c={compC}/>} {currentEvidence.key==='intervention'&&<InterventionDetail d={compD}/>} {currentEvidence.key==='history'&&<HistoryDetail e={compE}/>} {currentEvidence.key==='coding'&&<CodingDetail a={compA}/>}<button className="v3-full-btn" onClick={()=>setTechnicalOpen(true)}>View technical calculation</button></aside></div>}

    {selectedJourney&&<div className="v3-overlay" onClick={()=>setSelectedJourney(null)}><aside className="v3-mini-drawer" onClick={e=>e.stopPropagation()}><div className="v3-drawer-header"><div><span>{selectedJourney.formattedDateTime}</span><h2>{selectedJourney.title}</h2><p>{selectedJourney.subtitle}</p></div><button onClick={()=>setSelectedJourney(null)}><X/></button></div><div className="v3-detail-list">{selectedJourney.details.map(d=><div key={d}><CheckCircle2 size={16}/><span>{d}</span></div>)}</div></aside></div>}

    {technicalOpen&&<div className="v3-overlay" onClick={()=>setTechnicalOpen(false)}><div className="v3-modal wide" onClick={e=>e.stopPropagation()}><div className="v3-drawer-header"><div><span>TECHNICAL AUDIT VIEW</span><h2>How the {data.signalResult.score}/100 signal was calculated</h2><p>Backend-calculated scoring, suppressors, data quality and audit version.</p></div><button onClick={()=>setTechnicalOpen(false)}><X/></button></div><div className="v3-technical-table">{data.technicalBreakdown.rows.map(row=><div key={row.component}><span>{row.label}</span><strong>{row.bandAndDescription}</strong><b>{row.scoreDisplay}</b></div>)}</div><div className="v3-tech-note"><Info size={17}/><p>Raw score: {data.suppressors.rawScore}. Final score: {data.suppressors.finalScore}. {data.suppressors.applied.length?`Applied suppressors: ${data.suppressors.applied.map(s=>s.name).join(', ')}.`:'No suppressor ceiling applied.'} Model {data.audit.modelVersion} · Rules {data.audit.rulesVersion}.</p></div></div></div>}

    {reviewOpen&&<div className="v3-overlay" onClick={()=>setReviewOpen(false)}><div className="v3-modal" onClick={e=>e.stopPropagation()}><div className="v3-drawer-header"><div><span>HUMAN REVIEW</span><h2>Review this case</h2><p>This action is persisted to the backend review workflow.</p></div><button onClick={()=>setReviewOpen(false)}><X/></button></div><div className="form-grid"><label className="v3-field"><span>Reviewer ID *</span><input value={reviewerId} onChange={e=>setReviewerId(e.target.value)} placeholder="Authenticated/user directory ID"/></label><label className="v3-field"><span>Reviewer name *</span><input value={reviewerName} onChange={e=>setReviewerName(e.target.value)} placeholder="Reviewer name"/></label></div><label className="v3-field"><span>Reviewer outcome</span><select value={decision} onChange={e=>setDecision(e.target.value as ReviewOutcome|'')}><option value="">Choose an outcome</option>{reviewOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="v3-field"><span>Rationale</span><textarea value={rationale} onChange={e=>setRationale(e.target.value)} rows={5} placeholder="Explain the decision and cite the relevant evidence..."/></label><div className="v3-modal-actions"><button className="v3-secondary-btn" onClick={()=>setReviewOpen(false)}>Cancel</button><button className="v3-primary-btn" disabled={!decision||!rationale.trim()||!reviewerId.trim()||!reviewerName.trim()||actionBusy} onClick={saveReview}>{actionBusy?'Saving…':'Save review'}</button></div></div></div>}

    {notesOpen&&<div className="v3-overlay" onClick={()=>setNotesOpen(false)}><div className="v3-modal small" onClick={e=>e.stopPropagation()}><div className="v3-drawer-header"><div><span>CASE NOTE</span><h2>Add reviewer note</h2><p>{notes.length} existing note(s)</p></div><button onClick={()=>setNotesOpen(false)}><X/></button></div><div className="form-grid"><label className="v3-field"><span>Author name *</span><input value={reviewerName} onChange={e=>setReviewerName(e.target.value)} /></label><label className="v3-field"><span>Role *</span><input value={reviewerRole} onChange={e=>setReviewerRole(e.target.value)} /></label></div><label className="v3-field"><span>Note</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={7} placeholder="Write a note about this claim..."/></label><div className="v3-modal-actions"><button className="v3-secondary-btn" onClick={()=>setNotesOpen(false)}>Cancel</button><button className="v3-primary-btn" disabled={!note.trim()||!reviewerName.trim()||!reviewerRole.trim()||actionBusy} onClick={saveNote}>{actionBusy?'Saving…':'Add note'}</button></div></div></div>}

    {searchOpen&&<div className="v3-overlay" onClick={()=>setSearchOpen(false)}><div className="v3-modal small" onClick={e=>e.stopPropagation()}><div className="v3-drawer-header"><div><span>FIND IN CASE</span><h2>Jump to evidence</h2></div><button onClick={()=>setSearchOpen(false)}><X/></button></div><div className="v3-search-hints"><span>Evidence:</span>{data.findingsCards.map(f=><button key={f.key} onClick={()=>{setSearchOpen(false);setSelectedEvidence(f.key)}}>{f.title}</button>)}</div></div></div>}
  </div>
}

function PathRows({expected,actual}:{expected:string[];actual:string[]}){const render=(xs:string[],alert=false)=><div>{xs.map((x,i)=><span key={`${x}-${i}`} style={{display:'contents'}}><b className={alert&&i>=Math.max(1,xs.length-2)?'v3-node-alert':''}>{x}</b>{i<xs.length-1&&<ArrowRight/>}</span>)}</div>;return <><div className="v3-path-row expected"><span>Expected</span>{render(expected.length?expected:['Not available'])}</div><div className="v3-path-row actual"><span>Actual</span>{render(actual.length?actual:['Not available'],true)}</div></>}
function TimingDetail({b}:{b:any}){return <><div className="v3-detail-list"><div><Clock3/><span>Admission: {new Date(b.admissionDateTime).toLocaleString()}</span></div><div><Clock3/><span>First observed: {b.firstObservedDateTime?new Date(b.firstObservedDateTime).toLocaleString():'Unavailable'}</span></div><div><CheckCircle2/><span>{b.elapsedHoursFromAdmission??'—'} hours after admission · {b.band} · {b.points}/{b.maxPoints}</span></div></div><p>{b.reasoning}</p></>}
function PathDetail({c}:{c:any}){return <><PathRows expected={c.expectedPathway||[]} actual={c.actualPathway||[]}/><div className="v3-ai-box"><BrainCircuit/><div><span>AI supporting evidence</span><strong>{c.aiEvidenceAvailable?`${c.pathwaySimilarityPercent??'—'}% pathway similarity`:'AI model not connected — no AI score is generated'}</strong><p>{c.aiEvidenceStatus}. Business outcome remains {c.outcome}.</p></div></div></>}
function InterventionDetail({d}:{d:any}){const labels:[string,number,string][]=[['Nothing',0,'NO_INTERVENTION'],['Imaging only',8,'IMAGING_OR_DIAGNOSTIC_ONLY'],['Unplanned operation',14,'UNPLANNED_OPERATION'],['Rescue',20,'HIGH_ACUITY_RESCUE'],['Return to theatre',25,'RETURN_TO_THEATRE']];return <><div className="v3-intervention-scale">{labels.map(([l,p,k])=><div key={k} className={d.category===k?'active':''}><span>{l}</span><b>{p}</b></div>)}</div><div className="v3-detail-list">{d.modifiers?.map((m:any)=><div key={m.type}><CheckCircle2/><span>{m.type}: +{m.points} · {m.reason}</span></div>)}</div></>}
function HistoryDetail({e}:{e:any}){return <div className="v3-detail-list"><div><CheckCircle2/><span>History available: {e.historyAvailable?'Yes':'No'}</span></div><div><History/><span>Lookback searched: {e.lookbackDaysSearched} days</span></div><div><Info/><span>{e.outcomeLabel} · {e.points}/{e.maxPoints}. {e.reasoning}</span></div></div>}
function CodingDetail({a}:{a:any}){return <><div className="v3-code-card"><span>Diagnosis on claim</span><strong>{a.code}</strong><p>{a.description}</p></div><div className="v3-detail-list"><div><GitBranch/><span>{a.band} · {a.bandLabel} · {a.points}/{a.maxPoints}</span></div><div><Info/><span>{a.reasoning}</span></div></div></>}
