import { FileUp, Filter, MoreHorizontal, Pencil, Plus, Search, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { hacApi } from '../api/hacApi';
import type { ReviewQueueResponse, ReviewStatus, SignalLevel } from '../api/hacTypes';
import { ConfirmDialog, useToast } from '../components/Feedback';
import { PageHeader, RiskBadge, StatusBadge } from '../components/UI';

export default function Claims(){
  const nav=useNavigate(), toast=useToast(), fileRef=useRef<HTMLInputElement|null>(null);
  const [data,setData]=useState<ReviewQueueResponse|null>(null), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [search,setSearch]=useState(''), [level,setLevel]=useState<SignalLevel|''>(''), [status,setStatus]=useState<ReviewStatus|''>('');
  const [page,setPage]=useState(1), [refresh,setRefresh]=useState(0), [filtersOpen,setFiltersOpen]=useState(false), [deleteId,setDeleteId]=useState<string|null>(null), [busy,setBusy]=useState(false);
  useEffect(()=>{const t=setTimeout(()=>{setLoading(true);setError('');hacApi.getReviewQueue({page,pageSize:10,search,signalLevel:level,reviewStatus:status}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},180);return()=>clearTimeout(t)},[page,search,level,status,refresh]);
  const remove=async()=>{if(!deleteId)return;setBusy(true);try{await hacApi.deleteClaim(deleteId);toast.show('success','Claim deleted',`${deleteId} was removed from persistent storage.`);setDeleteId(null);setRefresh(v=>v+1)}catch(e:any){toast.show('error','Delete failed',e.message)}finally{setBusy(false)}};
  const clearFilters=()=>{setSearch('');setLevel('');setStatus('');setPage(1)}; const hasFilters=!!(search||level||status);

  const importClaims=async(file?:File)=>{if(!file)return;setBusy(true);try{const text=await file.text();const parsed=JSON.parse(text);const rows=Array.isArray(parsed)?parsed:parsed.claims;if(!Array.isArray(rows))throw new Error('JSON must be an array or an object containing a claims array.');const r=await hacApi.importClaims(rows);toast.show('success','Claims imported',`${r.count} claim(s) were validated and persisted.`);setPage(1);setRefresh(v=>v+1)}catch(e:any){toast.show('error','Import failed',e.message)}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}};

  return <>
    <PageHeader title="Review Queue" subtitle="Only claims that were actually entered or imported into this environment appear here." actions={<div className="header-actions"><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={e=>importClaims(e.target.files?.[0])}/><button className="btn outline" disabled={busy} onClick={()=>fileRef.current?.click()}><FileUp size={15}/>Import claims</button><button className="btn primary" onClick={()=>nav('/claims/new')}><Plus size={16}/>Add claim</button></div>}/>
    <div className="queue-overview card"><div><span>LIVE WORKFLOW</span><strong>Cases requiring investigation</strong><p>The queue is calculated from the persistent backend claim store. No seed/demo records are injected.</p></div><div className="queue-kpis"><button className={!status&&!level?'active':''} onClick={()=>{setStatus('');setLevel('')}}><b>{data?.summaryCounts.total??'—'}</b><span>All</span></button><button className={level==='HIGH'?'active':''} onClick={()=>{setLevel('HIGH');setStatus('');setPage(1)}}><b>{data?.summaryCounts.highPriority??'—'}</b><span>High priority</span></button><button className={status==='IN_REVIEW'?'active':''} onClick={()=>{setStatus('IN_REVIEW');setLevel('');setPage(1)}}><b>{data?.summaryCounts.inReview??'—'}</b><span>In review</span></button><button className={status==='CONFIRMED'?'active':''} onClick={()=>{setStatus('CONFIRMED');setLevel('');setPage(1)}}><b>{data?.summaryCounts.confirmed??'—'}</b><span>Confirmed</span></button></div></div>
    <div className="filter-card card queue-filters"><label className="field-shell field-search"><span>Search cases</span><div><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Claim ID, patient, diagnosis or provider…"/>{search&&<button type="button" className="clear-input" onClick={()=>setSearch('')}><X size={14}/></button>}</div></label><label className="field-shell"><span>Signal level</span><select value={level} onChange={e=>{setLevel(e.target.value as any);setPage(1)}}><option value="">All signal levels</option><option value="HIGH">High</option><option value="REVIEW">Review</option><option value="MONITOR">Monitor</option><option value="NONE">None</option></select></label><button className={`btn outline filter-toggle ${filtersOpen?'active':''}`} onClick={()=>setFiltersOpen(v=>!v)}><SlidersHorizontal size={16}/>More filters</button>{hasFilters&&<button className="text-button" onClick={clearFilters}>Clear filters</button>}</div>
    {filtersOpen&&<div className="advanced-filter-panel card"><Filter size={17}/><label className="field-shell"><span>Review status</span><select value={status} onChange={e=>{setStatus(e.target.value as any);setPage(1)}}><option value="">All workflow statuses</option><option value="NEW">New</option><option value="IN_REVIEW">In review</option><option value="NEED_MORE_INFORMATION">Need more information</option><option value="CONFIRMED">Confirmed</option><option value="RESOLVED">Resolved</option><option value="MONITORING">Monitoring</option></select></label><div><strong>Server-side filtering</strong><span>The API performs the search, filters and pagination.</span></div></div>}
    {loading&&<div className="card api-state">Loading claims…</div>}
    {error&&<div className="card api-state api-error"><strong>Could not load claims</strong><span>{error}</span></div>}
    {!loading&&!error&&data&&<div className="card table-card responsive-table"><table><thead><tr><th>Claim</th><th>Patient</th><th>Admission</th><th>Suspected condition</th><th>Score</th><th>Priority</th><th>Workflow</th><th>Provider</th><th></th></tr></thead><tbody>{data.items.map(c=><tr key={c.claimId} className="clickable-row"><td onClick={()=>nav(`/claims/${c.claimId}`)}><strong className="table-link">{c.claimId}</strong><small className="table-subtext">Open investigation</small></td><td onClick={()=>nav(`/claims/${c.claimId}`)}>{c.patientId}</td><td onClick={()=>nav(`/claims/${c.claimId}`)}>{new Date(c.admissionDateTime).toLocaleDateString()}</td><td onClick={()=>nav(`/claims/${c.claimId}`)}><strong>{c.hacDiagnosisCode}</strong><small className="table-subtext">Primary: {c.primaryDiagnosisCode}</small></td><td onClick={()=>nav(`/claims/${c.claimId}`)}><span className="score-pill">{c.score}</span></td><td onClick={()=>nav(`/claims/${c.claimId}`)}><RiskBadge risk={c.signalLevel}/></td><td onClick={()=>nav(`/claims/${c.claimId}`)}><StatusBadge status={c.reviewStatus.replaceAll('_',' ')}/></td><td onClick={()=>nav(`/claims/${c.claimId}`)}>{c.providerDisplayName}</td><td><div className="row-actions"><button title="Open investigation" className="icon-btn" onClick={()=>nav(`/claims/${c.claimId}`)}><MoreHorizontal size={17}/></button><button title="Edit source data" className="icon-btn" onClick={()=>nav(`/claims/${c.claimId}/edit`)}><Pencil size={15}/></button><button title="Delete claim" className="icon-btn danger" onClick={()=>setDeleteId(c.claimId)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{data.items.length===0&&<div className="empty-state"><Search size={24}/><strong>{hasFilters?'No claims match these filters':'No claims have been loaded yet'}</strong><span>{hasFilters?'Clear filters to broaden the results.':'Add or import an actual claim to begin. The system does not generate demo cases.'}</span>{hasFilters?<button className="btn outline" onClick={clearFilters}>Clear filters</button>:<button className="btn primary" onClick={()=>nav('/claims/new')}><Plus size={15}/>Add first claim</button>}</div>}<div className="table-footer"><span>{data.pagination.total} matching case(s)</span><div className="pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><button className="active">{page}</button><button disabled={page>=data.pagination.totalPages} onClick={()=>setPage(p=>p+1)}>›</button></div></div></div>}
    <ConfirmDialog open={!!deleteId} title={`Delete ${deleteId||'claim'}?`} message="This permanently removes the claim and its notes/review decisions from this environment." confirmLabel="Delete claim" danger busy={busy} onCancel={()=>setDeleteId(null)} onConfirm={remove}/>
  </>;
}
