import { BookOpenCheck, CheckCircle2, FileUp, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { hacApi } from '../api/hacApi';
import type { ReferenceCategory, ReferenceCodeRecord } from '../api/hacTypes';
import { ConfirmDialog, Modal, useToast } from '../components/Feedback';
import { PageHeader } from '../components/UI';

const categoryLabels:Record<ReferenceCategory,string>={CARE_EVENT:'Care event',DEVICE_DRUG:'Device / drug',SUBSTITUTION_WATCHLIST:'Substitution watchlist',INJURY:'Injury',COMPLICATION_LIST:'Complication list',OTHER:'Other'};
const emptyForm:Partial<ReferenceCodeRecord>={code:'',description:'',category:'CARE_EVENT',internalBand:'A1',scoreContribution:20,active:true,rationale:'',source:''};

export default function CodeReference(){
  const toast=useToast(), fileRef=useRef<HTMLInputElement|null>(null);
  const [items,setItems]=useState<ReferenceCodeRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[category,setCategory]=useState('ALL'),[active,setActive]=useState('true'),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0);
  const [modal,setModal]=useState(false),[editing,setEditing]=useState<ReferenceCodeRecord|null>(null),[form,setForm]=useState<Partial<ReferenceCodeRecord>>(emptyForm),[saving,setSaving]=useState(false),[deleteItem,setDeleteItem]=useState<ReferenceCodeRecord|null>(null);
  const load=()=>{setLoading(true);setError('');hacApi.getReferenceCodes({search,category,active,page,pageSize:12}).then(r=>{setItems(r.items);setPages(r.pagination.totalPages);setTotal(r.pagination.total)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[search,category,active,page]);
  const openCreate=()=>{setEditing(null);setForm(emptyForm);setModal(true)}, openEdit=(x:ReferenceCodeRecord)=>{setEditing(x);setForm({...x});setModal(true)};
  const scoreHint=useMemo(()=>({A1:20,A2:16,A3:12,A4:10,A5:6,A6:0}[form.internalBand||'A1']),[form.internalBand]);
  const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const payload={...form,scoreContribution:Number(form.scoreContribution??scoreHint)};if(editing)await hacApi.updateReferenceCode(editing.id,payload);else await hacApi.createReferenceCode(payload);toast.show('success',editing?'Reference updated':'Reference added',`${payload.code} was saved to the persistent backend catalog.`);setModal(false);load()}catch(err:any){toast.show('error','Unable to save reference',err.message)}finally{setSaving(false)}};
  const remove=async()=>{if(!deleteItem)return;setSaving(true);try{await hacApi.deleteReferenceCode(deleteItem.id);toast.show('success','Reference deleted',`${deleteItem.code} was removed.`);setDeleteItem(null);load()}catch(err:any){toast.show('error','Delete failed',err.message)}finally{setSaving(false)}};
  const importFile=async(file?:File)=>{if(!file)return;try{const text=await file.text();const parsed=JSON.parse(text);const rows=Array.isArray(parsed)?parsed:parsed.items;if(!Array.isArray(rows))throw new Error('JSON must be an array or an object containing an items array.');const r=await hacApi.importReferenceCodes(rows);toast.show('success','Reference file imported',`${r.items.length} record(s) saved.`);setPage(1);load()}catch(err:any){toast.show('error','Import failed',err.message)}finally{if(fileRef.current)fileRef.current.value=''}};
  return <>
    <PageHeader title="Clinical Reference Catalog" subtitle="Only reference rules entered or imported into this environment are displayed." actions={<div className="header-actions"><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={e=>importFile(e.target.files?.[0])}/><button className="btn outline" onClick={()=>fileRef.current?.click()}><FileUp size={15}/>Import JSON</button><button className="btn primary" onClick={openCreate}><Plus size={16}/>Add reference rule</button></div>}/>
    <div className="info-banner"><BookOpenCheck size={19}/><div><strong>Persistent real-data catalog</strong><span>The system does not preload example codes. Add rules from your approved source or import an approved JSON catalog.</span></div></div>
    <div className="filter-card card"><label className="field-shell field-search"><span>Search</span><div><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Code, description, rationale or source…"/></div></label><label className="field-shell"><span>Signal category</span><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="ALL">All categories</option>{Object.entries(categoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field-shell"><span>Status</span><select value={active} onChange={e=>{setActive(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label><div className="filter-summary"><strong>{total}</strong><span>matching rules</span></div></div>
    {loading&&<div className="card api-state">Loading reference catalog…</div>}{error&&<div className="card api-state api-error"><strong>Could not load catalog</strong><span>{error}</span></div>}
    {!loading&&!error&&<div className="card table-card responsive-table"><table><thead><tr><th>Code</th><th>Description</th><th>Category</th><th>Internal scoring</th><th>Status</th><th>Source</th><th></th></tr></thead><tbody>{items.map(r=><tr key={r.id}><td><strong>{r.code}</strong><small className="table-subtext">Updated {new Date(r.updatedAt).toLocaleDateString()}</small></td><td><span className="desc-cell">{r.description}</span><small className="table-subtext">{r.rationale}</small></td><td><span className="category-chip">{categoryLabels[r.category]}</span></td><td><span className="score-rule"><b>{r.scoreContribution}</b><small>{r.internalBand} audit band</small></span></td><td>{r.active?<span className="status-chip active"><CheckCircle2 size={13}/>Active</span>:<span className="status-chip inactive">Inactive</span>}</td><td>{r.source}</td><td><div className="row-actions"><button className="icon-btn" title="Edit" onClick={()=>openEdit(r)}><Pencil size={15}/></button><button className="icon-btn danger" title="Delete" onClick={()=>setDeleteItem(r)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{items.length===0&&<div className="empty-state"><BookOpenCheck size={26}/><strong>No approved reference rules loaded</strong><span>Add a rule manually or import an approved JSON catalog. Nothing is populated automatically.</span><div className="header-actions"><button className="btn outline" onClick={()=>fileRef.current?.click()}><FileUp size={15}/>Import JSON</button><button className="btn primary" onClick={openCreate}><Plus size={15}/>Add first rule</button></div></div>}<div className="table-footer"><span>Page {page} of {pages}</span><div className="pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><button className="active">{page}</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>›</button></div></div></div>}
    <Modal open={modal} onClose={()=>setModal(false)} title={editing?'Edit reference rule':'Add reference rule'} subtitle="Every value should come from an approved clinical/coding source." size="lg" footer={<><button className="btn outline" onClick={()=>setModal(false)}>Cancel</button><button className="btn primary" form="reference-form" type="submit" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Add rule'}</button></>}>
      <form id="reference-form" onSubmit={save} className="form-grid polished-form"><label className="field-shell"><span>Diagnosis code *</span><input value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})} required/></label><label className="field-shell"><span>Signal category *</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value as ReferenceCategory})}>{Object.entries(categoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field-shell span-2"><span>Description *</span><input value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label className="field-shell"><span>Internal audit band *</span><select value={form.internalBand} onChange={e=>{const band=e.target.value as any;setForm({...form,internalBand:band,scoreContribution:({A1:20,A2:16,A3:12,A4:10,A5:6,A6:0} as any)[band]})}}>{['A1','A2','A3','A4','A5','A6'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field-shell"><span>Score contribution *</span><input required type="number" min="0" max="20" value={form.scoreContribution??scoreHint} onChange={e=>setForm({...form,scoreContribution:Number(e.target.value)})}/></label><label className="field-shell span-2"><span>Clinical rationale *</span><textarea rows={3} value={form.rationale||''} onChange={e=>setForm({...form,rationale:e.target.value})} required/></label><label className="field-shell span-2"><span>Approved source / reference *</span><input value={form.source||''} onChange={e=>setForm({...form,source:e.target.value})} placeholder="Guideline, policy, coding source, version…" required/></label><label className="toggle-field"><input type="checkbox" checked={form.active??true} onChange={e=>setForm({...form,active:e.target.checked})}/><span><strong>Active rule</strong><small>Only active exact-match rules are used by the reference service.</small></span></label></form>
    </Modal>
    <ConfirmDialog open={!!deleteItem} title={`Delete ${deleteItem?.code||'reference'}?`} message="This removes the rule from the persistent clinical reference catalog." confirmLabel="Delete rule" danger busy={saving} onCancel={()=>setDeleteItem(null)} onConfirm={remove}/>
  </>;
}
